# # # # # # # # # # # # # # # # # # # 
#                                   # 
#   This is an auto-generated file  # 
#   based on the jupyter notebook   # 
#
#   >   ``01_Gen_Distribution_Zoo.ipynb''
#
#                                   #
# # # # # # # # # # # # # # # # # # #

##################################### 
module GenDistributionZoo  
#####################################

using Gen

include("push_forward.jl"); # autogenerated from: "../src/push_forward.jl"
include("diag_normal.jl"); # autogenerated from: "../src/diag_normal.jl"
include("product_dist.jl"); # autogenerated from: "../src/product_dist.jl"

#####################################
end  
#####################################
